# Generated by Django 3.2 on 2021-04-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200813_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[('vitamins', 'Vitamins'), ('paracetamol', 'Paracetamol')], max_length=255, verbose_name='Type'),
        ),
    ]
